[project]
name = "intellibuild-mozilla"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "any-agent>=1.18.0",
    "chromadb>=1.5.9",
    "encoderfile>=0.6.2",
    "mcp>=1.27.2",
    "mcpd>=0.1.0",
    "numpy>=2.4.6",
    "openai>=2.41.1",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.50",
]
