from typing import List, Optional, Literal
from pydantic import BaseModel, Field

class PromptTokensDetails(BaseModel):
    cached_tokens: Optional[int] = Field(default=0, description="Number of cached prompt tokens")

class Usage(BaseModel):
    completion_tokens: int = Field(..., description="Tokens used for the completion")
    prompt_tokens: int = Field(..., description="Tokens used in the prompt")
    total_tokens: int = Field(..., description="Total tokens used (prompt + completion)")
    prompt_tokens_details: Optional[PromptTokensDetails] = Field(
        default=None, 
        description="Detailed breakdown of prompt tokens"
    )

class Message(BaseModel):
    role: Literal["system", "user", "assistant", "tool"] = Field(
        ..., 
        description="The role of the message author (e.g., assistant, user, system)"
    )
    content: str = Field(..., description="The content of the message")

class Choice(BaseModel):
    index: int = Field(..., description="The index of the choice in the list of choices")
    message: Message = Field(..., description="The message generated by the model")
    finish_reason: Optional[str] = Field(
        default=None, 
        description="The reason the model stopped generating tokens"
    )

class Timings(BaseModel):
    cache_n: Optional[int] = None
    prompt_n: Optional[int] = None
    prompt_ms: Optional[float] = None
    prompt_per_token_ms: Optional[float] = None
    prompt_per_second: Optional[float] = None
    predicted_n: Optional[int] = None
    predicted_ms: Optional[float] = None
    predicted_per_token_ms: Optional[float] = None
    predicted_per_second: Optional[float] = None

class ChatCompletionResponse(BaseModel):
    id: str = Field(..., description="A unique identifier for the chat completion")
    object: Literal["chat.completion"] = Field(
        default="chat.completion", 
        description="The object type, which is always chat.completion"
    )
    created: int = Field(..., description="The Unix timestamp (in seconds) of when the chat completion was created")
    model: str = Field(..., description="The model used for the chat completion")
    system_fingerprint: Optional[str] = Field(
        default=None, 
        description="The system fingerprint of the backend serving the model"
    )
    choices: List[Choice] = Field(..., description="A list of chat completion choices")
    usage: Usage = Field(..., description="Usage statistics for the completion request")
    timings: Optional[Timings] = Field(
        default=None, 
        description="Performance timings (specific to local execution servers like llamafile/Llama.cpp)"
    )

    @property
    def assistant_content(self) -> Optional[str]:
        """Helper property to easily extract the main assistant response text."""
        if self.choices and len(self.choices) > 0:
            return self.choices[0].message.content
        return None
